development:
  host: '127.0.0.1'
  port: 9042
  keyspace: address_book_development

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: address_book_test

production:
  hosts:
    - 'cass1.address_book.biz'
    - 'cass2.address_book.biz'
    - 'cass3.address_book.biz'
  port: 9042
  keyspace: address_book_production
  username: 'myappuser'
  password: 'password1'
